version: '3'

services:
  weserv:
    image: ghcr.io/weserv/images:5.x
    restart: always
    expose:
      - '8080'
    shm_size: '1gb'
    networks:
      - weserv
    dns:
      - 1.1.1.1

networks:
  weserv:
